#!/bin/bash

KPATH="$HOME/Library/Developer/Xcode/DerivedData/Sinetek-rtsx-bpnguoevveybdhfrrjjdpfweiiwu/Build/Products/Debug"
KPATH2="`dirname $0`/../DerivedData/Build/Products/Debug"
KEXT="Sinetek-rtsx.kext"

if [ -d "$KEXT" ]; then
	sudo rm -rf "$KEXT"
fi

# copy and set uid/gid
if [ -d "$KPATH/$KEXT" ]; then
	echo "Copying from Xcode's DerivedData..."
	cp -r "$KPATH/$KEXT" ./
elif [ -d "$KPATH2/$KEXT" ]; then
	echo "Copying from project-local DerivedData..."
	cp -r "$KPATH2/$KEXT" ./
fi
sudo chown -R root:wheel "$KEXT"
