#ifndef SINETEK_RTSX_OPENBSD_OPENBSD_COMPAT_QUEUE_H
#define SINETEK_RTSX_OPENBSD_OPENBSD_COMPAT_QUEUE_H

// SIMPLEQ -> STAILQ
#define SIMPLEQ_EMPTY       STAILQ_EMPTY
#define SIMPLEQ_ENTRY       STAILQ_ENTRY
#define SIMPLEQ_FIRST       STAILQ_FIRST
#define SIMPLEQ_FOREACH     STAILQ_FOREACH
#define SIMPLEQ_HEAD        STAILQ_HEAD
#define SIMPLEQ_INIT        STAILQ_INIT
#define SIMPLEQ_INSERT_TAIL STAILQ_INSERT_TAIL
#define SIMPLEQ_NEXT        STAILQ_NEXT

#endif // SINETEK_RTSX_OPENBSD_OPENBSD_COMPAT_QUEUE_H
